---
- hosts: jenkins
  remote_user: ec2-user
  become: yes
  become_user: root
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.jenkins

